version: '2'
services:

  firefox61:
    image: selenium/node-firefox:3.13.0-argon
    # See https://github.com/SeleniumHQ/docker-selenium#running-the-images
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1366
      SCREEN_HEIGHT: 1020
      FIREFOX_VERSION: 61.0.1
      GECKODRIVER_VERSION: 0.21.0

  chrome68:
    image: selenium/node-chrome:3.13.0-argon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1366
      SCREEN_HEIGHT: 1020
      CHROME_VERSION: google-chrome-stable=68.0.3440.75
      CHROME_DRIVER_VERSION: 2.40

  # Selenium Grid/Hub
  hub:
    image: selenium/hub:3.13.0-argon

  # Local instance of TopHat test site
  tophat:
    build: .
    command: npm start

  # Tests
  tests:
    build: .
    links:
      - hub
      - tophat
    volumes:
      - ./docker-output/screenshots/taken:/tests/screenshots/taken
      - ./docker-output/screenshots/diff:/tests/screenshots/diff
      - ./docker-output/errorShots:/tests/errorShots
    environment:
      - SITE=tophat
      - BASE_URL=http://tophat:8000/
      - accountsUsername
      - accountsPassword
      - BROWSERSTACK_USERNAME
      - BROWSERSTACK_ACCESS_KEY
      - TEAMCITY_VERSION
    container_name: tophat_tests
